// Media / contributed articles data.
// Newest items should be placed first.

const ARTICLES = [
  {
    date: '2026-04-08',
    cat: '寄稿',
    title: '〈電子黒板の活用〉展開図は「動かして」覚える——立方体11種類が操作できるDigital geneで図形授業が変わる',
    source: 'Kokuban BASE',
    description: '「展開図が苦手」を解消するインタラクティブ教材Digital geneを紹介。電子黒板上で、立方体の展開図11種類をスライダーで動かし、折る・展開する・視点を変える操作で空間認識が育つ。インストール不要でそのまま授業に使える。',
    url: 'https://kokuban-base.com/columns/digital-gene/',
    image: 'images/media/takeyama-01.png',
  },
  {
    date: '2026-03-25',
    cat: '寄稿',
    title: '少子化で伸びる塾、潰れる塾 数字で見る学習塾市場の二極化',
    source: '英俊社',
    description: 'データから読み解く学習塾業界の現在地と未来。少子化でも市場が横ばいである理由、そして激化する二極化の正体を暴きます。大手塾が勢力を伸ばす一方、地域の中小塾には「独自の強み」と「変化への適応」が求められています。中学受験ニーズの地域格差や学習塾費の推移など、経営戦略の指針となる最新動向をまとめました。',
    url: 'https://kawasemi.eisyun.jp/cram-school-polarization/',
    image: 'images/media/takeyama-02.png',
  },
  {
    date: '2026-02-05',
    cat: '寄稿',
    title: '【対談の後日談】電子黒板を選ぶ基準は“スペック”ではなく“設計思想”だった',
    source: 'Kokuban BASE',
    description: '「どの電子黒板も同じ」と思っていませんか？合理性のStarBoard、シンプル極まるSHARP、自由なBenQ、安心のMIRAI TOUCH。各社の設計思想を読み解き、学習塾の武器になる一台をナビゲート。中立的な立場で比較できるKokuban BASEが、最適なパートナー選びをサポートします。',
    url: 'https://kokuban-base.com/columns/denshikokuban-gakushujuku/',
    image: 'images/media/takeyama-03.jpg',
  },
  {
    date: '2025-12-02',
    cat: '取材',
    title: '【対談】世界50万台の実績 電子黒板「StarBoard」が選ばれる理由とは？',
    source: 'Kokuban BASE',
    description: '「機能が増えると操作が難しい」と諦めていませんか？世界80カ国で導入されるStarBoardは、なぜ多機能なのに直感的に使えるのか。AI活用や教材作成の時短テクニック、最大110インチの画面サイズなど、授業の質と効率を劇的に変える「現場ファースト」の秘密に迫ります。',
    url: 'https://kokuban-base.com/columns/starboard-ideaspot-education-talk/',
    image: 'images/media/takeyama-04.png',
  },
  {
    date: '2025-11-11',
    cat: '取材',
    title: '国内インターナショナルスクールシェアNo.1 Gemini搭載電子黒板 BenQ Boardが選ばれる理由とは？',
    source: 'Kokuban BASE',
    description: '世界中の教育現場の声から生まれた電子黒板「BenQ Board」。国内インターナショナルスクールでトップシェアを誇る理由とは？Google AI「Gemini」との連携機能や、目に優しいブルーライトカット、抗菌仕様など、世界標準の機能と安全性を徹底解剖します。',
    url: 'https://kokuban-base.com/columns/benq-ideaspot-education-talk/',
    image: 'images/media/takeyama-05.png',
  },
  {
    date: '2025-07-13',
    cat: '寄稿',
    title: '高校無償化で塾経営はどう変わる？進路選択と教育費の変化への対応戦略と実践策',
    source: '英俊社',
    description: '「高校無償化は家庭の進路選択にどのような影響を与えたか」という観点から、高校無償化による市場変化を整理し、学習塾が取るべき実践的な経営戦略を提言します。',
    url: 'https://kawasemi.eisyun.jp/free-high-scool-changes/',
    image: 'images/media/takeyama-06.jpg',
  },
  {
    date: '2025-01-07',
    cat: '寄稿',
    title: '【2025年版】学習塾の教材は紙とデジタルのどちらがよいのか。デジタル教材の選び方',
    source: '英俊社',
    description: 'さまざまな学術論文の知見を参照しながら、「学習塾の教材は紙がよいのか、デジタルがよいのか」という問いに一定の答えを提示します。その上で、どのようにデジタル教材の採否を判断すべきか、私なりの基準を紹介します。',
    url: 'https://kawasemi.eisyun.jp/teaching_materials/',
    image: 'images/media/takeyama-07.jpg',
  },
  {
    date: '2024-09-25',
    cat: '寄稿',
    title: 'もう集客に困らない！学習塾の集客できるキャッチコピーのつくり方を徹底解説！',
    source: '英俊社',
    description: '「指導力には自信があるが、集客には苦戦している」という塾経営者の方を対象に、チラシやWebサイトに掲載するキャッチコピーのつくり方を解説します。',
    url: 'https://kawasemi.eisyun.jp/catchphrase/',
    image: 'images/media/takeyama-08.jpg',
  },
  {
    date: '2024-05-23',
    cat: '寄稿',
    title: '模試の結果は統計で捉えよう！難関校指導のプロ講師が実践する成績データの分析法',
    source: '英俊社',
    description: '難関校の受験指導を担うプロの講師として、生徒の成績データを読み解く上で重要な統計的知識を解説します。そのうえで、実際にどのような観点からデータを読んでいるのか、その考え方の一部をご紹介したいと思います。',
    url: 'https://kawasemi.eisyun.jp/statistics/',
    image: 'images/media/takeyama-09.jpg',
  },
  {
    date: '2024-02-21',
    cat: '寄稿',
    title: '教え方のうまい講師は何が違うのか。講師の指導力を育て、難関校合格に繋げる５つのデータ活用',
    source: '英俊社',
    description: '今回はあえて「難関校への合格」ということに焦点を当て、教育者であり、経営者でもある私たちができることを考えたいと思います。',
    url: 'https://kawasemi.eisyun.jp/data-utilization/',
    image: 'images/media/takeyama-10.jpg',
  },
  {
    date: '2024-01-10',
    cat: '寄稿',
    title: '学習塾講師が選ぶおすすめノートアプリ4選！手書きノートのデジタル化で生産性を向上',
    source: '英俊社',
    description: '学習塾における手書きノートアプリの選び方やおすすめの活用法について、過去10年以上学習塾におけるICT活用に取り組んできた講師の視点で解説します。',
    url: 'https://kawasemi.eisyun.jp/tablet-use/',
    image: 'images/media/takeyama-11.jpg',
  },
  {
    date: '2023-11-29',
    cat: '寄稿',
    title: '圧倒的成約率の実現 ～創業を軌道に乗せる、顧客視点の塾経営実践',
    source: '英俊社',
    description: '創業期、今回ご紹介することに取り組むことで弊塾では70%超える高い成約率を実現しました。学習塾の開塾一年目から現在に至るまで、黒字経営を続けることができています。そこで今回は、体験授業や体験教室、問い合わせからの「圧倒的な成約率」を弾き出すために集客をはじめる前に取り組むべきことについてお話します。',
    url: 'https://kawasemi.eisyun.jp/cv-up-ksf/',
    image: 'images/media/takeyama-12.jpg',
  },
  {
    date: '2021-10-01',
    cat: '取材',
    title: '塾教材ＤＸ化最前線 〜英俊社×ｉｄｅａ ｓｐｏｔ×エプソンの事例から〜',
    source: '私塾界TV',
    description: 'ＩＣＴ教材を販売する企業２社と、それを活用する学習塾１社が登壇。ＩＣＴ教材からは、セイコーエプソン Ｐ事業戦略推進部の原基彰氏、英俊社の金子直純氏、学習塾からはｉｄｅａ ｓｐｏｔ（イデアスポット） 代表の竹山隼矢氏が参加した。三者が協働して取り組んだ事業の課題と、成果とは？',
    url: 'https://www.youtube.com/watch?v=vt-2JYvr3QQ',
    image: 'images/media/takeyama-13.png',
  },
  {
    date: '2021-02-19',
    cat: '取材',
    title: 'エプソンの遠隔印刷＋個別プリントにより、コロナ禍でも従来と引けを取らない第一志望校合格率85％を達成！',
    source: 'セイコーエプソン株式会社',
    description: '株式会社 idea spotは、セイコーエプソン株式会社と協力し、同社の「Epson Connect」を活用したリモート印刷およびスキャンtoクラウド機能を導入いたしました。',
    url: 'https://openinnovation.epson.com/topics/20210219_1/',
    image: 'images/media/takeyama-14.jpg',
  },
  {
    date: '2021-01-31',
    cat: '取材',
    title: '【対談】EPSON × ideaspot 子供たちにとって何が出来るか-教育領域へのイノベーション',
    source: 'セイコーエプソン株式会社',
    description: '「子どものために何ができるか」を原点に、教育とテクノロジーの融合を考える。株式会社 idea spot・竹山氏とエプソン・原氏が、デジタル化で変わる学習塾の役割や、地域による教育格差の解消について対談。教育の本質に迫る対話録です。',
    url: 'http://openinnovation.epson.com/vision/education/',
    image: 'images/media/takeyama-15.jpg',
  },
];
